---
title: "Advanced R DDEA"
author: "Ingrid M. Wagnon"
format: html
---

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets"))
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Making a table

```{r}
lipidomics |>
  group_by(metabolite) |>
  summarise(across(value, list(mean = mean, sd = sd))) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |>
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |>
  select(Metabolite = metabolite, `Mean SD` = MeanSD)
```

```{r}
create_table_descriptive_stats(lipidomics)
```

## Results: Basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and standard deviation of metabolites in the lipidomics dataset."
  )
```

## Plot of distributions

```{r}
ggplot(lipidomics, aes(x = value)) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") +
  theme_minimal()
```

```{r}
create_plot_distributions(lipidomics)
```

## Results: Distribution plot

```{r}
#| fig-cap: "Plot Distribution"
tar_read(plot_distributions)
```

## Preparing the data

```{r}
lipidomics |>
  count(code, metabolite) |>
  filter(n > 1)
```

```{r}
lipidomics |>
  group_by(pick(-value)) |>
  summarise(value = mean(value), .groups = "keep") |>
  ungroup()
```

```{r}
clean(lipidomics)
```

```{r}
lipidomics
```

```{r}
lipidomics |>
  filter(metabolite == "Cholesterol") |>
  mutate(
    class = as.factor(class),
    value = scale(value)
  )
```

```{r}
just_cholesterol <- lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess()

glm(
  formula = class ~ value,
  data = just_cholesterol,
  family = binomial
) |>
  broom::tidy(exponentiate = TRUE) |>
  mutate(
    metabolite = unique(just_cholesterol$metabolite),
    model = format(class ~ value),
    .before = everything()
  )
```

```{r}
lipidomics |>
  filter(metabolite == "Cholesterol") |>
  preprocess() |>
  fit_model(class ~ value)
```
